name: two_beauty
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  cached_network_image: ^3.2.1
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.0
  intl: ^0.17.0
  timeago: ^3.2.2
  url_launcher: ^6.1.2
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.15
  google_maps_flutter: ^2.1.5
  geolocator: ^8.2.1
  provider: ^6.0.2
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  http_interceptor: ^1.0.2
  flutter_bloc: ^8.0.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  equatable: ^2.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  injectable_generator: ^1.5.3
  build_runner: ^2.1.11
  mocktail: ^0.3.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/locations.json