name: two_beauty
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0
  font_awesome_flutter:
  google_fonts: ^2.1.0
  intl: ^0.17.0
  page_transition: ^2.0.4
  timeago: ^3.1.0
  url_launcher: ^6.0.12
  flutter_svg: ^1.0.0
  shrink_sidemenu: ^2.0.0+1-null-safety
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.8
  flare_flutter: ^3.0.2
  google_maps_flutter: ^2.1.1
  geolocator: ^8.0.0
  provider: ^6.0.1
  map_launcher: ^2.1.1
  json_serializable: ^6.1.0
  json_annotation: ^4.4.0
  date_picker_timeline: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/locations.json